library/urls.py
from django.conf.urls.defaults import *
from django.views.generic import list_detail
from library.models import (Text, Collection, Entry)


text_dict = {
    'queryset' : Text.objects.all(),
}

raw_text_dict = {
    'queryset' : Text.objects.all(),
    'template_name': 'library/raw_text_detail.html',
    'mimetype': 'text/plain'
}

collection_dict= {
    'queryset' : Collection.objects.all(),
}

entries_dict = {
    'queryset' : Entry.objects.all(),
}

urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url': '/pages/index/'}),
    url(r'^texts/$', list_detail.object_list, text_dict, 'library-text-list'),
    url(r'^texts/(?P<slug>[-\w]+).md/$', list_detail.object_detail, raw_text_dict, 'library-raw-text-detail'),
    url(r'^texts/(?P<slug>[-\w]+)/$', list_detail.object_detail, text_dict, 'library-text-detail'),

    url(r'^entries/(?P<slug>[-\w]+)/$', list_detail.object_detail, entries_dict, 'library-entry-detail'),

    url(r'^collections/$', list_detail.object_list, collection_dict, 'library-collection-list'),
    url(r'^collections/(?P<slug>[-\w]+)/$', list_detail.object_detail, collection_dict, 'library-collection-detail')
)

library/models.py
from django.utils.translation import ugettext as _
from django.db import models
from django.template.defaultfilters import slugify
from publications.models import Publication
from hvad.models import TranslatableModel, TranslatedFields


STATUS_SELECTED = 0
STATUS_FURTHER_READING = 1
STATUS_MAYBE = 2


STATUS_CHOICES = (
    (STATUS_SELECTED, "Selected"),
    (STATUS_FURTHER_READING, "Further reading"),
    (STATUS_MAYBE, "Maybe"),
)

class License(models.Model):
    """
    Represents a license.
    """
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    body = models.TextField(blank=True)
    
    def __unicode__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=25)
    iso_code = models.CharField(max_length=2)
    def __unicode__(self):
        return self.name

class Text(models.Model):
    """
    Represents a text.
    """
    reference = models.ForeignKey(Publication)
    slug = models.SlugField(max_length=255, blank=True)
    body = models.TextField(blank=True)
    license = models.ForeignKey(License)
    
    def __unicode__(self):
        return self.reference.title

    class Meta:
        ordering = ['slug']
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.reference.title)
        super(Text, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
         return ('library-text-detail', [self.slug])

class Translation(models.Model):
    """
    Represents a translation relationship.
    """
    text = models.ForeignKey(Text)
    language = models.ForeignKey(Language)
    translation = models.ForeignKey(Publication)

class Image(models.Model):
    text = models.ForeignKey(Text)
    caption = models.CharField(max_length=255)
    image = models.FileField(upload_to="images", max_length=255, verbose_name='image file')

class Collection(models.Model):
    """
    Represents a collection.
    """
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    body = models.TextField(blank=True)
    texts = models.ManyToManyField(Text, through="Membership")
    order = models.PositiveIntegerField(blank=True, null=True)
    
    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['order']
    
    @models.permalink
    def get_absolute_url(self):
        return ('library-collection-detail', [self.slug])


class Membership(models.Model):
    text = models.ForeignKey(Text)
    collection = models.ForeignKey(Collection)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=0)
    order = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        ordering = ['order']
    
    def __unicode__(self):
        return self.text.reference.title


class Type(TranslatableModel):
    slug = models.SlugField(max_length=255, blank=True)
    translations = TranslatedFields(
        name = models.CharField(max_length=255),
    )



class Entry(TranslatableModel):
    MONTH_CHOICES = (
        ( 1, _('January')),
        ( 2, _('February')),
        ( 3, _('March')),
        ( 4, _('April')),
        ( 5, _('May')),
        ( 6, _('June')),
        ( 7, _('July')),
        ( 8, _('August')),
        ( 9, _('September')),
        (10, _('October')),
        (11, _('November')),
        (12, _('December'))
    )
    slug = models.SlugField(max_length=255, blank=True)
    type = models.ForeignKey(Type)
    authors = models.CharField(max_length=2048, help_text='List of authors separated by commas or <i>and</i>.')

    translations = TranslatedFields(
        title = models.CharField(max_length=512),
        book_title = models.CharField(max_length=256, blank=True),

        license = models.ForeignKey(License, blank=True, null=True),

        year = models.PositiveSmallIntegerField(max_length=4),
        month = models.PositiveSmallIntegerField(choices=MONTH_CHOICES, blank=True, null=True),

        abstract = models.TextField(blank=True),
        body = models.TextField(blank=True),

        editors = models.CharField(max_length=2048, blank=True, help_text=""),
        publisher = models.CharField(max_length=256, blank=True),

        pdf = models.FileField(upload_to='publications/', verbose_name='PDF', blank=True, null=True),
        url = models.URLField(blank=True, verify_exists=False, verbose_name='URL', help_text='Link to PDF or journal page.'),
        volume = models.IntegerField(blank=True, null=True),
        number = models.IntegerField(blank=True, null=True, verbose_name='Issue number'),
        #pages = PagesField(max_length=32, blank=True),
        pages = models.CharField(max_length=32, blank=True),
        journal = models.CharField(max_length=256, blank=True),
    )

    #def __unicode__(self):
        #return self.title

    class Meta:
        pass
        #app_label = _('publications')
        #ordering = ['-year', '-month', '-id']

library/views.py
# Create your views here.

library/templates/library/base.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{{ object }}{% endblock %} — LGRU Reader</title>
    <link href="{{ STATIC_URL }}lib/css/reset.css" type="text/css" rel="stylesheet">
    <link href="{{ STATIC_URL }}less/font.less" type="text/css" rel="stylesheet/less">
    <link href="{{ STATIC_URL }}less/reader.less" type="text/css" rel="stylesheet/less">
    <LINK rel="stylesheet" type="text/css" href="{{ STATIC_URL }}font/font.css">

</head>
<body>

    <aside id="left">
        
        <div id='logo'><a href="/">Considering<br/>your&nbsp;tools</a></div>
<!-- <img src="http://ospublish.constantvzw.org/blog/wp-content/uploads/lgru-coposition-25-02-dualcirclespng.png" /> -->
        <nav>
            <a href="/pages/about/">About</a>
        </nav>
        <nav>
            <ul>
                <!--<li>
                    <a href="{% url library-text-list %}">Texts</a>
                </li>
                <li>-->
                    <a href="{% url library-collection-list %}">Chapters</a>
                </li>
            </ul>	
        </nav>
        <div id="extra-aside">
            {% block extra_aside %}{% endblock %}
        </div>
    </aside>

    {% block body %}{% endblock %}

    {% block js %}
    <script src="{{ STATIC_URL }}lib/js/less-1.3.0.min.js"></script>
    <script src="{{ STATIC_URL }}lib/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}lib/js/jquery-ui.min.js"></script>
    <!--<script src="{{ STATIC_URL }}lib/js/jquery.tocify.min.js"></script>-->
    <script src="{{ STATIC_URL }}lib/js/jquery.tocify.min.js"></script>
    {% endblock %}

<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://stats.stdin.fr/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "12"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
</body>
</html>

library/templates/library/collection_detail.html
{% extends "library/base.html" %}

{% load markup %}
{% load publication_extras %}


{% block title %}{{ object.name }}{% endblock %}


{% block extra_aside %}
    <h2>{{ object }}</h2>
    <div id="toc"></div>
{% endblock %}


{% block body %}
    <article>
    <h1>{{ object.name }}</h1>
    <section>
        {{ object.body|markdown:"extra" }}

    </section>
    <hr>
        <h1>Contents</h1>
    <section>
        <ul class='text-list'>
        {% for text in object.membership_set.all %}
            <li class='{% if object.body %}has-content{% endif %} {% if not user.is_authenticated and text.text.license_id < 3 %}not-authorized{% endif %}'>
            {% with text.text.reference as publication %}

            <h2><a href="{{ text.text.get_absolute_url }}" class="title">{{ publication.title|tex_parse }}</a></h2>

            {% if text.text.translation_set.all %}
                <div class="translations">
                    {% for trad in text.text.translation_set.all %}
                        <a href='{{ trad.translation.text_set.all.0.get_absolute_url }}'>{{ trad.language }}</a>
                        {% if not forloop.last %}/{% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            <p>
                {% for author, author_escaped in publication.authors_escaped %}
                <span class="author">{{ author }}</span>{% if not forloop.last %}{% if forloop.revcounter == 2 %}{% if not forloop.first %},{% endif %} and {% else %}, {% endif %}{% endif %}
            {% endfor %}
            </p>

            <p>
            {% if publication.journal %}
                <cite>{{ publication.journal }}, {{ publication.year }}</cite><br />
            {% else %}
                <i>{% if publication.book_title %}{{ publication.book_title }},{% endif %}
                {% if publication.publisher %}{{ publication.publisher }},{% endif %}
                {{ publication.year }}</i><br/>
            {% endif %}
            {% if publication.keywords %}
                {% for keyword, keyword_escaped in publication.keywords_escaped %}
                    <a class="keyword" href="/publications/tag/{{ keyword_escaped }}/">{{ keyword }}</a>
                {% endfor %}
            {% endif %}
            </p>

            <p>
            {% if publication.code %}<a class="link" href="{{ publication.code }}">Code</a>,{% endif %}
            {% if publication.url %}<a class="link" rel="external" href="{{ publication.url }}">URL</a>,{% endif %}
            {% if text.text.license_id > 2 %}
                {% if publication.pdf %}<a class="link" href="{{ MEDIA_URL }}{{ publication.pdf }}">PDF</a>,{% endif %}
            {% elif user.is_authenticated %}
                {% if publication.pdf %}<a class="link" href="{{ MEDIA_URL }}{{ publication.pdf }}">PDF</a>,{% endif %}
            {% endif %}
            {% if publication.doi %}<a class="link" rel="external" href="http://dx.doi.org/{{ publication.doi }}">DOI</a>,{% endif %}
            {% endwith %}

            {{ text.text.license }}
            </p>
            </li>
        {% endfor %}
        </ul>
    </section>
    </article>
{% endblock %}



{% block js %}
{{ block.super }}

<script>
$(function () {
    $("#toc").tocify({
        context: 'article',
        selectors: 'h2, h3',
    });
});
</script>
{% endblock %}

library/templates/library/collection_list.html
{% extends "library/base.html" %}

{% load markup %}
{% load publication_extras %}


{% block title %}Chapters{% endblock %}

{% block extra_aside %}
    {% for object in object_list %}
        <h2><a href="{{ object.get_absolute_url }}">{{ object }}</a></h2>
    {% endfor %}
{% endblock %}



{% block body %}
<article>
    {% for object in object_list %}
        <section class='text-list'>
        <h1><a href="{{ object.get_absolute_url }}">{{ object }}</a></h1>
    
        <ul>
        {% for text in object.membership_set.all %}
            <li class='{% if object.body %}has-content{% endif %} {% if not user.is_authenticated and text.text.license_id < 3 %}not-authorized{% endif %}'>
            {% with text.text.reference as publication %}

            <h2><a href="{{ text.text.get_absolute_url }}" class="title">{{ publication.title|tex_parse }}</a></h2>

            {% if text.text.translation_set.all %}
                <div class="translations">
                    {% for trad in text.text.translation_set.all %}
                        <a href='{{ trad.translation.text_set.all.0.get_absolute_url }}'>{{ trad.language }}</a>
                        {% if not forloop.last %}/{% endif %}
                    {% endfor %}
                </div>
            {% endif %}

            <p>
            {% for author, author_escaped in publication.authors_escaped %}
                <span class="author">{{ author }}</span>{% if not forloop.last %}{% if forloop.revcounter == 2 %}{% if not forloop.first %},{% endif %} and {% else %}, {% endif %}{% endif %}
            {% endfor %}
            </p>

            <p>
            {% if publication.journal %}
                <cite>{{ publication.journal }}, {{ publication.year }}</cite><br />
            {% else %}
                <i>{% if publication.book_title %}{{ publication.book_title }},{% endif %}
                {% if publication.publisher %}{{ publication.publisher }},{% endif %}
                {{ publication.year }}</i><br/>
            {% endif %}
            {% if publication.keywords %}
                {% for keyword, keyword_escaped in publication.keywords_escaped %}
                    <a class="keyword" href="/publications/tag/{{ keyword_escaped }}/">{{ keyword }}</a>
                {% endfor %}
            {% endif %}
            </p>
            <p>
            {% if publication.code %}<a class="link" href="{{ publication.code }}">Code</a>,{% endif %}
            {% if publication.url %}<a class="link" rel="external" href="{{ publication.url }}">URL</a>,{% endif %}
            {% if text.text.license_id > 2 %}
                {% if publication.pdf %}<a class="link" href="{{ MEDIA_URL }}{{ publication.pdf }}">PDF</a>,{% endif %}
            {% elif user.is_authenticated %}
                {% if publication.pdf %}<a class="link" href="{{ MEDIA_URL }}{{ publication.pdf }}">PDF</a>,{% endif %}
            {% endif %}
            {% if publication.doi %}<a class="link" rel="external" href="http://dx.doi.org/{{ publication.doi }}">DOI</a>,{% endif %}
            {% endwith %}

            {{ text.text.license }}
            </p>

            </li>
        {% endfor %}
        </ul>
        </section>
    {% endfor %}
    </article>
{% endblock %}

library/templates/library/entry_detail.html
<!DOCTYPE HTML>{% load markup publication_extras %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{{ object }}{% endblock %} — LGRU Reader</title>
    <link href="{{ STATIC_URL }}lib/css/reset.css" type="text/css" rel="stylesheet">
    <link href="{{ STATIC_URL }}less/font.less" type="text/css" rel="stylesheet/less">
    <link href="{{ STATIC_URL }}less/reader.less" type="text/css" rel="stylesheet/less">
</head>
<body>
    {% if object.translations.all %}
    this text is available available in {% for translation in object.translations.all %}
        {{ translation.language_code }}
    {% endfor %}
    
    {% endif %}
    <article>
    <h1>{{ object.title }}</h1>
    {{ object.body|markdown }}
    </article>

    {% block js %}
    <script src="{{ STATIC_URL }}lib/js/less-1.3.0.min.js"></script>
    <script src="{{ STATIC_URL }}lib/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}lib/js/jquery-ui.min.js"></script>
    {% endblock %}
</body>
</html>

library/templates/library/partial/metadata.html
{% load publication_extras %}

<div id="article-title"><h1>{{ publication.title|tex_parse }}</h1><br />-<br />

<h1>
{% for author, author_escaped in publication.authors_escaped %}
  <span class="author">{{ author }}</span>{% if not forloop.last %}{% if forloop.revcounter == 2 %}{% if not forloop.first %},{% endif %} and {% else %}, {% endif %}{% endif %}
{% endfor %}
</h1>

{% if publication.journal %}
   <cite>{{ publication.journal }}</cite>, <time>{{ publication.year }}</time>
{% else %}
    {% if publication.book_title %}<cite>{{ publication.book_title }}</cite>,{% endif %}
    {% if publication.publisher %}{{ publication.publisher }},{% endif %}
    <time><h2>{{ publication.year }}</h2></time>
{% endif %}

 <h2>{{ object.license }}</h2><br />

{% if publication.keywords %}
    {% for keyword, keyword_escaped in publication.keywords_escaped %}
        <a class="keyword" href="/publications/tag/{{ keyword_escaped }}/">{{ keyword }}</a>
    {% endfor %}

{% endif %}

{% if object.translation_set.all %}

    {% for trad in object.translation_set.all %}
       <h2> <a href='{{ trad.translation.text_set.all.0.get_absolute_url }}'>{{ trad.language }}</a></h2>
        {% if not forloop.last %}/{% endif %}
    {% endfor %}
{% endif %}

{% comment %}
{% if publication.code %}<a class="link" href="{{ publication.code }}">Code</a>,{% endif %}
{% if publication.url %}<a class="link" rel="external" href="{{ publication.url }}">URL</a>,{% endif %}
{% if publication.pdf %}<a class="link" href="{{ MEDIA_URL }}{{ publication.pdf }}">PDF</a>,{% endif %}
{% if publication.doi %}<a class="link" rel="external" href="http://dx.doi.org/{{ publication.doi }}">DOI</a>,{% endif %}
{% endcomment %}
</div>

library/templates/library/raw_text_detail.html
{{ object.body|safe }}

library/templates/library/text_detail.html
{% extends "library/base.html" %}


{% load markup publication_extras %}


{% block extra_aside %}
    {% if object.collection_set.all %}
        {% with object.collection_set.all.0 as coll %}
            <h2><a href='{{ coll.get_absolute_url }}'>{{ coll }}</a></h2>

            {% for member in coll.membership_set.all %}
                {% with member.text.reference as publication %}
                {% if publication == object.reference %}
                    <div id="current">
                        <div class="metadata">

                            <cite id="article-title" style="color:red;" >{{ publication.title|tex_parse }}</cite><br>
                            {#{% include "library/partial/metadata.html" %}#}
                            
                        </div>
                        
                        
                    </div>
                {% else %}
               
                    <div class="other">
                        <a href="{{ member.text.get_absolute_url }}"><cite>{{ publication.title|tex_parse }}</cite></a>
                    </div>
                {% endif %}
                {% endwith %}
            {% endfor %}
            </ul>   
        {% endwith %}
    {% else %}
        {% with object.translation_set.all.0.translation.text_set.all.0.collection_set.all.0 as coll %} 
            <h2><a href='{{ coll.get_absolute_url }}'>{{ coll }}</a></h2>

            {% for member in coll.membership_set.all %}
                {% with member.text.reference as publication %}
                {% if publication == object.reference.translation_set.all.0.text.reference %}
                    <div id="current">
                        <div class="metadata">
                        <!--<div id="toc"></div>-->
                            <cite id="article-title">{{ publication.title|tex_parse }}</cite><br>
                            {#{% include "library/partial/metadata.html" %}#}
                        </div>
                        <hr>
                        
                    </div>
                {% else %}
                    <div class="other">
                        <a href="{{ member.text.get_absolute_url }}"><cite>{{ publication.title|tex_parse }}</cite></a>
                    </div>
                {% endif %}
                {% endwith %}
            {% endfor %}
            </ul>   
        {% endwith %}
    {% endif %}

{% endblock %}
	
{% block body %}
    
      
    <article id="main">
    <div class="article-header">
        <div id="toc"></div>
    <div id="article-title">
 
      <h1>{{ object.reference.title }}<br/>-</h1>
      <div class="authors">{{ object.reference.authors }}</div>
      <div class="year">{{ object.reference.year }} / {{ object.license }}</div>
    </div>
    </div>
    <div class="article-contenu">
	{% if not object.body %}
	    No content available yet.
	{% endif %}

	{% if object.license_id <= 2 and not user.is_authenticated %}
	    We do not have the rights to publish this text. <br />
	    Please refer to available URL and metadata when possible.
	{% else%}
	    {{ object.body|markdown:"extra" }}
	{% endif %}
    </div>
    </article>
{% endblock %}


{% block js %}
{{ block.super }}

<script>
$(function () {
    $("#toc").tocify({
        context: 'article',
        selectors: 'h2, h3',
        
      });
});
//     $(document).ready(function(){
//         side = $("aside#left");
//         txt = $("article#main");
//         side_h = side.height();
//         txt_h = txt.height();
//         //console.log(side_h)
//         //console.log(txt_h)
//         //console.log($(document).scrollTop());
//         //console.log($(window).height())
//         if(side_h > $(window).height()){
//             $(document).scroll(function(){
//                 if ($(document).scrollTop() + $(window).height()*1.5 > side_h ){
//                     side.css({'position': 'fixed', 'bottom': '1em'});
//                     txt.css({'position': 'absolute', 'margin-left': '13em'});
//                 } else {
//                     side.css({'position': 'static'});
//                 }
//              });
//         } else {
//            side.css({'position': 'fixed', 'top': '1em'});
//             txt.css({'position': 'absolute', 'margin-left': '13em'});
//         }
//     });


</script>
{% endblock %}

library/templates/library/text_list.html
{% extends "library/base.html" %}
{% load markup %}
{% load publication_extras %}

{% block body %}
<article>
    <h1>Texts</h1>
    <section>
        <ul class="text-list">
            {% for object in object_list %}
                {% with object.reference as publication %}
                    <li class='{% if object.body %}has-content{% endif %} {% if not user.is_authenticated and object.license_id < 3 %}not-authorized{% endif %}'>{{ publication.authors }}. <br />
                    <a href="{{ object.get_absolute_url }}">{{ publication.title }}{% if not publication.title_ends_with_punct %}.{% endif %}</a><br />
                    {% if publication.journal %} {{ publication.journal }},{% endif %}{% if publication.book_title %} {{ publication.book_title }},{% endif %}{% if publication.publisher %} {{ publication.publisher }},{% endif %}{% if publication.volume %} volume {{ publication.volume }},{% endif %}{% if publication.number %} issue {{ publication.number }},{% endif %}{% if publication.pages %} pages {{ publication.pages }},{% endif %}{% if publication.month %} {{ publication.month_long }}{% endif %} {{ publication.year }}.<br />
                    {{ object.license }}
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
    </section>
</article>
{% endblock %}